name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 🩼
        run: 'bun install @esbuild/linux-x64 sass-embedded-linux-x64 --dev --no-save'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}


      - name: Create Service Account file
        run: |
          echo "${{ secrets.FIRESTORE_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > apps/server/service-account.json

      - name: Install dependencies
        run: bun install

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps chromium

      - name: Lint
        run: bun run lint

      - name: Test
        run: |
          bun run dev & # Start in background
          bunx wait-on http://localhost:5173
          bun run test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30